# This is a basic workflow to help you get started with Actions

name: Create and cache

# Controls when the workflow will run
on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      content_value:
        type: string
        description: File content value
        required: true
env:
  CONTENT_VALUE: inputs.content_value
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Create file
        run: echo "SCOPENAME=$CONTENT_VALUE" >> test.properties

      # Runs a set of commands using the runners shell
      - name: Cache file
        uses: actions/cache@v4
        with: 
          path: test.properties
          key: test-properties
