# This is a basic workflow to help you get started with Actions

name: Download and read

# Controls when the workflow will run
on:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ github.token }}
  GITHUB_REPOSITORY: ${{ github.repository }}
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      #- run: sudo apt-get -y install jq
      
      - name: Download artifact
        run: |
          gh api /repos/$GITHUB_REPOSITORY/actions/artifacts --jq '.artifacts[0].workflow_run.id' >> id.txt
          gh run download $(cat id.txt) -D ~/

      - name: Run id
        run: cat id.txt
      
      - name: Show results
        run: cat cache-data/test.properties
          
