name: Create second file and upload it

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      CONTENT_VALUE:
        type: string
        description: File content value
        required: true
env:
  CONTENT_VALUE: inputs.content_value
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "REPOSITORY_TEST_VAR=TEST" >> $GITHUB_ENV
