name: Second create and upload

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      CONTENT_VALUE:
        type: string
        description: File content value
        required: true
env:
  CONTENT_VALUE: ${{ inputs.content_value }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create file
        run: echo "FILE_CONTENT=$CONTENT_VALUE" >> test.properties

      - name: Upload file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cache-data
          path: ~/work/cache-test/cache-test/test.properties
