# This is a basic workflow to help you get started with Actions

name: test var

# Controls when the workflow will run
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.CLI_TOKEN }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create file
        run: echo "noice" >> test.properties

      # Runs a single command using the runners shell
      - name: Change var
        run: gh variable set REPOSITORY_TEST_VAR -b $(cat test.properties)
