# This is a basic workflow to help you get started with Actions

name: test var

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      varValue:
        type: string
        required: true
permissions: write-all
env:
  VAR_VALUE: ${{ inputs.varValue }}
  GH_TOKEN: ${{ github.token }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create file
        run: echo "noice" >> test.properties

      # Runs a single command using the runners shell
      - name: Change var
        run: gh variable set REPOSITORY_TEST_VAR -b $(cat test.properties)__$VAR_VALUE
