# This is a basic workflow to help you get started with Actions

name: Use cache

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ github.token }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Download cache
        uses: actions/cache/restore@v3
        with:
          path: test.properties
          key: test-properties

      - name: Print content from cache in std-output
        run: cat test.properties

      - name: Move
        run: sudo mv /home/runner/work/cache-test/cache-test/test.properties /

      - name: List root
        run: ls -l /

      - name: PWD
        run: pwd

      - name: Delete cache
        run: | 
          gh cache delete test-properties
